### PR TITLE
Support Austrian German in Analyzer Language

### PR DESCRIPTION
**Pull request by mikeselander**
Adds Austrian German to the mapping of analyzer languages.

### CODE REVIEW

**Comment by mikeselander** [comment]
@joehoyle / @rmccue I could use this update for a current upgrade client; would it be possible to get this merged and updated early this week?

**Comment by joehoyle** [comment]
@mikeselander do you need this on 3.0, or an earlier release?

**Comment by mikeselander** [comment]
I need it 3.0 please 🙏

**Comment by joehoyle** [comment]
@mikeselander Ok published https://github.com/humanmade/altis-enhanced-search/releases/tag/3.0.2 you'll just need to run `composer update altis/enhanced-search` I believe.

**Comment by mikeselander** [comment]
Wonderful ❤️ It's really great how fast y'all can release this changes!

**Pull request merged**
