### PR TITLE
Add theme for tests

### PR DESCRIPTION
**Pull request by roborourke**
Should hopefully fix the test run, realised there's no default theme with local server and we're checking some front end stuff in these tests.

### CODE REVIEW

**Comment by roborourke** [comment]
🚀 🎉 🙌 💥

**Comment by roborourke** [comment]
We might want to consider adding a default theme to `module.yml` in the dev tools repo to keep things consistent and avoid needing to do too much of this kind of hack.

Also moving the `composer server start` to `before_script` would make it easy to use `composer server cli theme install ... -- --activate` for example.

**Review by shadyvb — APPROVED** [review]

**Comment by shadyvb** [comment]
I was going to suggest the same. Good thinking.

**Comment by roborourke** [comment]
Rapid :)

**Pull request merged**
